# Generated by Django 4.1.13 on 2024-01-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('COCH', 'Coche'), ('CICL', 'Ciclomotor'), ('MOTO', 'Motocicleta    ')], max_length=4)),
                ('chasis', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
